language: java
sudo: required
services:
  - docker
before_install:
  - sudo docker run --name db -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=practice -e MYSQL_USER=student -e MYSQL_PASSWORD=123 mysql
  - sudo docker build -t borlok/app .
  - sudo docker run --name spring -p 8080:8080 --link db borlok/app
script:
  - bundle exec rake test
